// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'list': string;
  'loading': string;
  'select-box': string;
  'selectBox': string;
  'selected': string;
}
export const cssExports: CssExports;
export default cssExports;
