// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'no-suggess': string;
  'noSuggess': string;
  'row-warning': string;
  'rowWarning': string;
}
export const cssExports: CssExports;
export default cssExports;
