export default {
    path: '/marketingCenter',
    name: '运营中心',
    icon: 'FundViewOutlined',
    routes: [{
        path: '/marketingCenter/activityManage',
        name: '活动管理',
        component: './MarketingCenter/ActivityManage',
        access: 'MENU_ACTIVITY_MANAGE',
    }, {
        path: '/marketingCenter/activityDetail',
        name: '活动详情',
        component: './MarketingCenter/ActivityDetail',
        access: 'MENU_ACTIVITY_DETAIL',
        hideInMenu: true
    }, {
        path: '/marketingCenter/hotSaleDetail',
        name: '爆款好物',
        component: './MarketingCenter/HotSaleDetail',
        access: 'MENU_HOT_SALE_DETAIL',
        hideInMenu: true
    }, {
        path: '/marketingCenter/flashSaleDetail',
        name: '限时抢购',
        component: './MarketingCenter/FlashSaleDetail',
        access: 'MENU_FLASH_SALE_DETAIL',
        hideInMenu: true
    }, {
        path: '/marketingCenter/shake',
        name: "摇一摇",
        component: './MarketingCenter/Shake',
        access: 'MENU_SHAKE'
    }, {
        path: '/marketingCenter/appSet',
        name: "APP配置",
        component: './MarketingCenter/AppSet',
        access: 'MENU_App_Set'
    }, {
        path: '/marketingCenter/hotSearch',
        name: '热搜词',
        component: './MarketingCenter/HotSearch',
        access: 'MENU_HOT_SEARCH'
    }, {
        path: '/marketingCenter/productManage',
        name: '模块商品管理',
        hideInMenu: true,
        component: './MarketingCenter/AppSet/components/productManage',
        access: 'MENU_MODULE_PRODUCT_MANAGE'
    }, {
        path: '/marketingCenter/coupon',
        name: '优惠券',
        component: './MarketingCenter/Coupon',
        access: 'MENU_COUPON',
        exact: true
    }, {
        path: '/marketingCenter/couponDetail',
        name: '优惠券详情',
        component: './MarketingCenter/CouponDetail',
        access: 'MENU_COUPON_DETAIL',
        exact: true,
        hideInMenu: true
    }, {
        path: '/marketingCenter/couponEdit',
        name: '新增优惠券',
        component: './MarketingCenter/CouponEdit',
        access: 'MENU_COUPON_EDIT',
        exact: true,
        hideInMenu: true
    }, {
        path: '/marketingCenter/couponPackageEdit',
        name: '新增优惠券包',
        component: './MarketingCenter/CouponPackageEdit',
        access: 'MENU_COUPON_PACKAGE_EDIT',
        exact: true,
        hideInMenu: true
    }]
}
