// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cate-list': string;
  'cateList': string;
  'label': string;
  'list': string;
  'selected': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
