// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkbox-label': string;
  'checkboxLabel': string;
  'container': string;
  'cur': string;
  'expand-select-box': string;
  'expand-select-container': string;
  'expand-select-wrap': string;
  'expandSelectBox': string;
  'expandSelectContainer': string;
  'expandSelectWrap': string;
}
export const cssExports: CssExports;
export default cssExports;
