// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'category-bot': string;
  'category-box': string;
  'category-list': string;
  'categoryBot': string;
  'categoryBox': string;
  'categoryList': string;
  'container': string;
  'create': string;
  'list': string;
  'selected': string;
  'selected-category': string;
  'selectedCategory': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
