// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action': string;
  'box': string;
  'container': string;
  'country-name': string;
  'countryName': string;
  'list': string;
  'require': string;
  'tip': string;
  'upload-box': string;
  'uploadBox': string;
}
export const cssExports: CssExports;
export default cssExports;
