// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'add-category': string;
  'addCategory': string;
  'ant-card-body': string;
  'ant-card-head': string;
  'antCardBody': string;
  'antCardHead': string;
  'box-card': string;
  'boxCard': string;
  'operate': string;
  'product-publish': string;
  'product-publish-wrapper': string;
  'productPublish': string;
  'productPublishWrapper': string;
  'publish-button': string;
  'publish-info': string;
  'publishButton': string;
  'publishInfo': string;
}
export const cssExports: CssExports;
export default cssExports;
