// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottom': string;
  'box': string;
  'changeSwipe': string;
  'close': string;
  'container': string;
  'list': string;
  'next': string;
  'prev': string;
  'show': string;
  'top': string;
}
export const cssExports: CssExports;
export default cssExports;
